### ISSUE TITLE
FileNotFoundException: cwebp_tmp/dwebp

### ISSUE THREAD

**Issue by STG284** [biezhi/webp-io#9]
```
io.github.biezhi.webp.WebpIOException: java.io.FileNotFoundException: cwebp_tmp/dwebp: open failed: ENOENT (No such file or directory)
        at io.github.biezhi.webp.WebpIO.init(WebpIO.java:58)
        at io.github.biezhi.webp.WebpIO.<init>(WebpIO.java:27)
        at io.github.biezhi.webp.WebpIO.create(WebpIO.java:63)
```

**Comment by CrackerKSR** [comment]
I think you must add those library files cwebp dwebp in the project. I think It looking for temp folder which is created by WebIo.java file (you can check that in src folder).

**Comment by hellokaton** [comment]
@STG284  I released a new version, do you still have that question?
